export interface BootLine {
  at: number
  text: string
  cls?: string
}

const ok = 'text-emerald-400'
const info = 'text-cyan-400'
const warn = 'text-amber-400'
const dim = 'text-slate-500'
const err = 'text-red-400'
const bright = 'text-slate-100'

export const IDS_BOOT: BootLine[] = [
  { at: 0,     text: 'YHLAS-SEC BIOS v2.14 (build 2025-08-14)', cls: bright },
  { at: 80,    text: 'Copyright (c) 2025 Yhlas Defense Systems',            cls: dim },
  { at: 260,   text: 'CPU: Intel(R) Xeon E-2388G @ 3.20GHz  8C/16T',        cls: dim },
  { at: 420,   text: 'Memory test : 16384MB .... [ OK ]',                   cls: dim },
  { at: 620,   text: 'Detecting storage devices ...',                       cls: dim },
  { at: 880,   text: '  /dev/nvme0n1   Samsung PM9A1 512GB   [ OK ]',       cls: dim },
  { at: 1040,  text: '  /dev/sda       WDC HC330 4TB         [ OK ]',       cls: dim },
  { at: 1260,  text: 'NIC: Intel I210 1Gbit  eth0  mac=52:54:00:a1:55:05',  cls: dim },
  { at: 1480,  text: 'Loading GRUB 2.06 ...',                               cls: dim },
  { at: 2100,  text: '  -> Rocky Linux 9.3 (Blue Onyx) — IDS Hardened',     cls: bright },
  { at: 3200,  text: '[    0.000000] Linux 5.14.0-362.24.1.el9.x86_64',     cls: info },
  { at: 3380,  text: '[    0.002314] Command line: BOOT_IMAGE=vmlinuz root=UUID=f3b9 ro audit=1 selinux=1 ids_profile=snort-eve', cls: dim },
  { at: 3620,  text: '[    0.214518] SELinux: Initializing security module', cls: info },
  { at: 3880,  text: '[    0.388741] smpboot: CPU0: Intel Xeon (family 6)', cls: dim },
  { at: 4120,  text: '[    0.512003] ACPI: Added _OSI(Module Device)',      cls: dim },
  { at: 4360,  text: '[    0.735920] PCI: Using host bridge windows from ACPI', cls: dim },
  { at: 4720,  text: '[    1.001234] usbcore: registered new interface driver usbhid', cls: dim },
  { at: 5200,  text: '[    1.412879] ext4-fs (nvme0n1p2): mounted filesystem with ordered data mode', cls: dim },
  { at: 6100,  text: 'Welcome to Rocky Linux 9.3 (Blue Onyx)!',             cls: ok },
  { at: 6500,  text: '[  OK  ] Reached target Swaps.',                      cls: ok },
  { at: 6900,  text: '[  OK  ] Reached target Local File Systems.',         cls: ok },
  { at: 7400,  text: '[  OK  ] Started Journal Service.',                   cls: ok },
  { at: 7900,  text: '[  OK  ] Started udev Kernel Device Manager.',        cls: ok },
  { at: 8500,  text: '         Starting Load Kernel Modules...',            cls: dim },
  { at: 9100,  text: '[  OK  ] Finished Load Kernel Modules.',              cls: ok },
  { at: 9700,  text: '         Starting Network Manager...',                cls: dim },
  { at: 10800, text: '[  OK  ] Started Network Manager.',                   cls: ok },
  { at: 11600, text: '         eth0: link is UP   1000Mb/s full-duplex',    cls: info },
  { at: 12400, text: '         eth0: IPv4 address 10.10.10.5/24',           cls: info },
  { at: 13300, text: '[  OK  ] Reached target Network is Online.',          cls: ok },
  { at: 14200, text: '         Starting OpenSSH server daemon...',          cls: dim },
  { at: 15100, text: '[  OK  ] Started OpenSSH server daemon (port 22).',   cls: ok },
  { at: 16000, text: '         Starting firewalld — dynamic firewall daemon...', cls: dim },
  { at: 17100, text: '[  OK  ] Started firewalld.',                         cls: ok },
  { at: 18200, text: '         Starting Auditd — Linux Audit daemon...',    cls: dim },
  { at: 19200, text: '[  OK  ] Started Auditd.',                            cls: ok },
  { at: 20400, text: '         Bringing up anomaly-detector.service ...',   cls: warn },
  { at: 21600, text: '   [ .. ] Loading CICIDS2017 feature schema (74 cols)', cls: dim },
  { at: 23100, text: '   [ .. ] Reading model artifact /models/lgbm_final.pkl (38.4 MB)', cls: dim },
  { at: 25400, text: '   [ OK ] LightGBM booster loaded — 500 trees, 7 classes', cls: ok },
  { at: 27000, text: '   [ .. ] Verifying label encoder (7 attack families)', cls: dim },
  { at: 28200, text: '   [ OK ] Label encoder validated',                   cls: ok },
  { at: 29800, text: '   [ .. ] Warming up inference graph ...',            cls: dim },
  { at: 32200, text: '   [ OK ] Warmup complete — median latency 0.7ms',    cls: ok },
  { at: 33800, text: '         Starting pcap-engine (libpcap 1.10.1) on eth0', cls: dim },
  { at: 35800, text: '   [ OK ] Promiscuous mode enabled',                  cls: ok },
  { at: 37200, text: '   [ OK ] Berkeley Packet Filter attached',           cls: ok },
  { at: 38800, text: '         Starting flow-reassembler ...',              cls: dim },
  { at: 40600, text: '   [ OK ] Flow reassembler ready (4096 hash buckets)', cls: ok },
  { at: 42400, text: '         Opening WebSocket endpoint /api/monitor/ws', cls: dim },
  { at: 44000, text: '   [ OK ] WebSocket listener bound on 0.0.0.0:4086',  cls: ok },
  { at: 45600, text: '         Registering threat classifier hooks ...',    cls: dim },
  { at: 47200, text: '   [ OK ] Defender module registered  (mode=DISABLED)', cls: warn },
  { at: 48800, text: '         Running self-check ...',                     cls: dim },
  { at: 50400, text: '   [ OK ] Signature DB consistent',                   cls: ok },
  { at: 51700, text: '   [ OK ] ML model response  score=0.998',            cls: ok },
  { at: 53000, text: '   [ OK ] Flow pipeline throughput  124k pps',        cls: ok },
  { at: 54400, text: '[  OK  ] Started anomaly-detector.service.',          cls: ok },
  { at: 55800, text: '         Reached target Multi-User System.',          cls: ok },
  { at: 57000, text: '         Reached target Graphical Interface.',        cls: ok },
  { at: 58400, text: 'Rocky Linux 9.3 (Blue Onyx) ids-node tty1',           cls: bright },
  { at: 59200, text: 'ids-node login: root',                                cls: bright },
  { at: 60000, text: 'Last login: Fri Apr 24 09:14:02 from console',        cls: dim },
  { at: 60700, text: '[root@ids-node ~]# tail -f /var/log/anomaly.log',     cls: bright },
  { at: 61500, text: '>>> IDS READY — listening for threats on eth0',       cls: ok },
]

export const TRAFFIC_BOOT: BootLine[] = [
  { at: 0,     text: 'YHLAS-WS BIOS v1.09  (client workstation)',           cls: bright },
  { at: 120,   text: 'CPU: AMD Ryzen 5 5600G  6C/12T',                      cls: dim },
  { at: 300,   text: 'Memory test : 16384MB .... [ OK ]',                   cls: dim },
  { at: 560,   text: 'Detecting devices:  nvme0n1  eth0  usb(hid,keyboard)', cls: dim },
  { at: 860,   text: 'Loading GRUB 2.06 ...',                               cls: dim },
  { at: 1500,  text: '  -> Ubuntu 22.04.3 LTS (Jammy Jellyfish)',           cls: bright },
  { at: 2600,  text: '[    0.000000] Linux 6.5.0-26-generic',               cls: info },
  { at: 2880,  text: '[    0.118542] ACPI: PM: Registering ACPI NVS region', cls: dim },
  { at: 3180,  text: '[    0.402117] PCI: Fabric connected — 12 devices',   cls: dim },
  { at: 3500,  text: '[    0.783991] usbcore: registered driver hub',       cls: dim },
  { at: 4000,  text: '[    1.022450] EXT4-fs (nvme0n1p2): mounted ordered',  cls: dim },
  { at: 5200,  text: 'Welcome to Ubuntu 22.04.3 LTS!',                      cls: ok },
  { at: 5800,  text: '[  OK  ] Reached target Local File Systems.',         cls: ok },
  { at: 6600,  text: '[  OK  ] Started Journal Service.',                   cls: ok },
  { at: 7500,  text: '         Starting NetworkManager ...',                cls: dim },
  { at: 8800,  text: '[  OK  ] Started NetworkManager.',                    cls: ok },
  { at: 9600,  text: '         eth0: DHCP request ...',                     cls: info },
  { at: 11000, text: '         eth0: address 192.168.1.42/24  gw 192.168.1.1', cls: info },
  { at: 12200, text: '         DNS configured:  1.1.1.1, 8.8.8.8',          cls: info },
  { at: 13300, text: '[  OK  ] Reached target Network is Online.',          cls: ok },
  { at: 14500, text: '         Starting systemd-timesyncd.service ...',     cls: dim },
  { at: 15800, text: '[  OK  ] Synchronized clock from pool.ntp.org',       cls: ok },
  { at: 17000, text: '         Starting GNOME Display Manager ...',         cls: dim },
  { at: 19200, text: '[  OK  ] Started GDM — graphical login enabled',      cls: ok },
  { at: 20600, text: '         Auto-login: user=employee   session=gnome',  cls: info },
  { at: 22400, text: '         Launching GNOME Shell ...',                  cls: dim },
  { at: 24800, text: '   [ OK ] Desktop environment up',                    cls: ok },
  { at: 26400, text: '         Starting Mozilla Firefox 124.0 ...',         cls: dim },
  { at: 29000, text: '   [ OK ] Browser profile loaded (employee/default-release)', cls: ok },
  { at: 30600, text: '         Starting Slack client 4.38.125 ...',         cls: dim },
  { at: 32600, text: '   [ OK ] Slack connected',                           cls: ok },
  { at: 34000, text: '         Starting traffic-simulator.service ...',     cls: dim },
  { at: 35800, text: '   [ .. ] Loading request scheduler',                 cls: dim },
  { at: 37400, text: '   [ .. ] Building URL corpus (14 endpoints)',        cls: dim },
  { at: 39200, text: '   [ OK ] HTTP worker pool ready (threads=8)',        cls: ok },
  { at: 40800, text: '   [ .. ] Resolving DNS for example.com, github.com, api.service.com', cls: dim },
  { at: 43200, text: '   [ OK ] DNS cache warm — 14 hosts resolved',        cls: ok },
  { at: 44800, text: '   [ .. ] TLS handshake test (api.service.com:443)',  cls: dim },
  { at: 47000, text: '   [ OK ] TLS 1.3 connection established',            cls: ok },
  { at: 48400, text: '   [ .. ] Measuring RTT to gateway ...',              cls: dim },
  { at: 50000, text: '   [ OK ] Mean RTT 2.4ms   jitter 0.3ms',             cls: ok },
  { at: 51400, text: '[  OK  ] Started traffic-simulator.service.',         cls: ok },
  { at: 52800, text: '         Reached target Graphical Interface.',       cls: ok },
  { at: 54200, text: 'Ubuntu 22.04.3 LTS ws-client tty1',                  cls: bright },
  { at: 55200, text: 'user@ws-client ~$  whoami',                           cls: bright },
  { at: 56000, text: 'employee',                                            cls: dim },
  { at: 57000, text: 'user@ws-client ~$  ip -br addr show eth0',            cls: bright },
  { at: 57800, text: 'eth0  UP  192.168.1.42/24 fe80::5054:ff:fe9c:1234/64', cls: dim },
  { at: 59000, text: 'user@ws-client ~$  echo "ready to browse"',           cls: bright },
  { at: 60000, text: 'ready to browse',                                     cls: ok },
  { at: 61000, text: '>>> WORKSTATION READY — generating benign traffic',   cls: ok },
]

export const ATTACKER_BOOT: BootLine[] = [
  { at: 0,     text: 'AMI BIOS v5.2.4  (adversary-lab)',                    cls: bright },
  { at: 200,   text: 'CPU: AMD Threadripper 1950X  16C/32T',                cls: dim },
  { at: 420,   text: 'Memory test : 32768MB .... [ OK ]',                   cls: dim },
  { at: 700,   text: 'VT-x/AMD-V .... enabled',                             cls: dim },
  { at: 960,   text: 'Loading GRUB 2.06 ...',                               cls: dim },
  { at: 1400,  text: '  -> Kali GNU/Linux 2025.1  (rolling)',               cls: err },
  { at: 2400,  text: '[    0.000000] Linux 6.6.15-amd64  #kali',            cls: info },
  { at: 2720,  text: '[    0.192448] Command line: BOOT_IMAGE=vmlinuz cryptodev=1 rng-core=1', cls: dim },
  { at: 3060,  text: '[    0.388215] AppArmor: initialized',                cls: dim },
  { at: 3420,  text: '[    0.622947] raw packet sockets: enabled',          cls: warn },
  { at: 3800,  text: '[    0.913220] iptables filter registered',           cls: dim },
  { at: 4300,  text: '[    1.244518] loading kernel module af_packet',      cls: dim },
  { at: 4900,  text: '[    1.640882] registered protocol family PF_PACKET', cls: dim },
  { at: 5800,  text: 'Welcome to Kali Linux 2025.1!',                       cls: err },
  { at: 6400,  text: '[  OK  ] Reached target Local File Systems.',         cls: ok },
  { at: 7100,  text: '[  OK  ] Started Journal Service.',                   cls: ok },
  { at: 7800,  text: '         Starting NetworkManager-dispatcher ...',     cls: dim },
  { at: 9000,  text: '[  OK  ] Started NetworkManager.',                    cls: ok },
  { at: 9800,  text: '         eth0: link UP   bringing interface online',  cls: info },
  { at: 11000, text: '         eth0: address 10.10.10.66/24  gw 10.10.10.1', cls: info },
  { at: 12000, text: '         MAC spoofed: aa:bb:cc:13:37:42  (macchanger)', cls: warn },
  { at: 13400, text: '[  OK  ] Reached target Network is Online.',          cls: ok },
  { at: 14800, text: '         Starting tor.service (onion routing) ...',   cls: dim },
  { at: 16800, text: '   [ OK ] Tor bootstrapped  100%  — SocksPort 9050',  cls: ok },
  { at: 18200, text: '         Loading attack framework ...',               cls: warn },
  { at: 19400, text: '   [ .. ] Importing nmap 7.94 NSE scripts (604 files)', cls: dim },
  { at: 21400, text: '   [ OK ] nmap script engine ready',                  cls: ok },
  { at: 22600, text: '   [ .. ] Staging hping3 raw-packet forge ...',       cls: dim },
  { at: 24200, text: '   [ OK ] hping3 v3.0.0 — SYN/ACK/FIN/UDP modes armed', cls: ok },
  { at: 25600, text: '   [ .. ] Loading hydra credential dictionaries ...', cls: dim },
  { at: 27400, text: '   [ OK ] rockyou.txt  14,344,391 entries  (loaded)',  cls: ok },
  { at: 28800, text: '   [ OK ] ssh-users.lst  1,024 entries  (loaded)',    cls: ok },
  { at: 30200, text: '   [ .. ] Initializing medusa brute engine ...',      cls: dim },
  { at: 31800, text: '   [ OK ] medusa 2.2 — 12 parallel threads',          cls: ok },
  { at: 33200, text: '   [ .. ] Metasploit framework starting ...',         cls: dim },
  { at: 36000, text: '   [ OK ] msf6 loaded — 2398 exploits / 1254 aux',    cls: ok },
  { at: 37600, text: '   [ .. ] Setting up C2 listener (multi/handler)',    cls: warn },
  { at: 39400, text: '   [ OK ] Reverse TCP handler on 10.10.10.66:4444',   cls: warn },
  { at: 40800, text: '   [ .. ] Building payload cache ...',                cls: dim },
  { at: 43400, text: '   [ OK ] Payloads cached: windows/x64/meterpreter/reverse_tcp', cls: ok },
  { at: 44800, text: '         Reconnaissance pre-flight ...',              cls: dim },
  { at: 46000, text: '   [ .. ] ARP sweep 10.10.10.0/24  ...',              cls: dim },
  { at: 48200, text: '   [ OK ] 3 hosts discovered  (10.10.10.5, .42, .66)', cls: ok },
  { at: 49600, text: '   [ .. ] Fingerprinting targets ...',                cls: dim },
  { at: 52000, text: '   [ OK ] 10.10.10.5   Linux  — IDS candidate',       cls: warn },
  { at: 53400, text: '   [ OK ] 10.10.10.42  Linux  — workstation',         cls: warn },
  { at: 54800, text: '[  OK  ] Reached target Multi-User System.',          cls: ok },
  { at: 56000, text: 'Kali GNU/Linux 2025.1 adversary tty1',                cls: bright },
  { at: 57000, text: 'root@adversary:~#  uname -a',                         cls: bright },
  { at: 57800, text: 'Linux adversary 6.6.15-amd64 #kali SMP x86_64 GNU/Linux', cls: dim },
  { at: 59000, text: 'root@adversary:~#  echo "weapons hot"',               cls: bright },
  { at: 60000, text: 'weapons hot',                                         cls: err },
  { at: 61000, text: '>>> ATTACKER READY — offensive toolkit online',       cls: err },
]
